name: Daily Commit

on:
  schedule:
    - cron: "25 18 * * *"
  workflow_dispatch: # Allow manual triggers

jobs:
  commit_job:
    runs-on: ubuntu-latest

    steps:
      # Step: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step: Add a commit with your email in the name
      - name: Commit change by 22f1001951@ds.study.iitm.ac.in
        run: |
          echo "Automated commit" >> daily_commit.txt
          git config --local user.email "adityasahu1124@gmail.com"
          git config --local user.name "Aditya-Kumar-Sahu"
          git add daily_commit.txt
          git commit -m "Daily automated commit"
          git push
